language: node_js
node_js:
- '10'

# by default install just yarn
before_install: . ./travis-install-yarn.sh
install:
    # make it colorful
    - export FORCE_COLOR=1
    # Install the dependencies
    - yarn

# set up build matrix
# specify jobs (stages are serial, and scripts are parallel within a stage)
jobs:
  # stop if given a reason
  fast-finish: true

  include:
  # tests only on master and on pull-request
  - stage: Tests
    name: Test Packages
  
    script:
        - 'yarn test'
